#!/bin/bash
BOLD_RED='\033[0;1;31m'
NC='\033[0m' # No Color
echo -e "\n#### INSTALLER AUTOGENERATED ####" >> ~/.bashrc

DATA_DIR=
if [ -z "$INSTALL_DATA_DIR" ]
then
  echo "Please enter the installer data directory:"
  read DATA_DIR
else
  echo "Installer data directory already set"
  DATA_DIR="$INSTALL_DATA_DIR"
fi

echo -e "export INSTALL_DATA_DIR=$DATA_DIR\n" >> ~/.bashrc
export INSTALL_DATA_DIR=$DATA_DIR

for dir in ./*_i/
do
  echo -e "${BOLD_RED}Installing $(echo ${dir:2} | cut -d'_' -f 1)${NC}"

  cd $dir
  if [ ! -x ./install.sh ]
  then
    chmod +x ./install.sh
  fi

  source ./install.sh

  cd ..

  echo -e "${BOLD_RED}Finished installing $(echo ${dir:2} | cut -d'_' -f 1)${NC}"
done

echo -e "\n################################" >> ~/.bashrc
