#!/bin/bash
DRY="1"
YES="1"

function usage()
{
  echo "./install.sh"
  echo -e "\t-h --help"
  echo -e "\t--dry\tDry run, does not install"
  echo -e "\t-y --yes\tYes to all install"
  echo ""
}

while [ "$1" != "" ]; do
  PARAM=`echo $1 | awk -F= '{print $1}'`
  VALUE=`echo $1 | awk -F= '{print $2}'`
  case $PARAM in
    -h | --help)
      usage
      exit
      ;;
    --dry)
      DRY="2"
      ;;
    -y | --yes)
      YES="2"
      ;;
    *)
      echo "ERROR: unknown parameter \"$PARAM\""
      usage
      exit 1
      ;;
  esac
  shift
done

BOLD_RED='\033[0;1;31m'
NC='\033[0m' # No Color
echo -e "\n#### INSTALLER AUTOGENERATED ####" >> ~/.bashrc

DATA_DIR=
if [ -z "$INSTALL_DATA_DIR" ]
then
  echo "Please enter the installer data directory:"
  read DATA_DIR
else
  echo "Installer data directory already set"
  DATA_DIR="$INSTALL_DATA_DIR"
fi

echo -e "export INSTALL_DATA_DIR=$DATA_DIR\n" >> ~/.bashrc
export INSTALL_DATA_DIR=$DATA_DIR

for dir in ./*_i/
do
  if [ $YES = '1' ]
  then
    echo -n "Install $(echo ${dir:2} | cut -d '_' -f 1) (y/n)? "
    read answer
  else
    answer='y'
  fi

  if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo -e "${BOLD_RED}Installing $(echo ${dir:2} | cut -d'_' -f 1)${NC}"

    cd $dir
    if [ ! -x ./install.sh ]
    then
      chmod +x ./install.sh
    fi

    if [ $DRY = '1' ]
    then
      source ./install.sh
    fi

    cd ..

    echo -e "${BOLD_RED}Finished installing $(echo ${dir:2} | cut -d'_' -f 1)${NC}"
  fi
done

echo -e "\n################################" >> ~/.bashrc

echo -e "${BOLD_RED}Done!${NC}"
