#!/bin/bash
BOLD_RED='\033[0;1;31m'
NC='\033[0m' # No Color

for dir in ./*_i/
do
  echo -e "${BOLD_RED}Uninstalling $(echo ${dir:2} | cut -d'_' -f 1)${NC}"

  cd $dir
  if [ ! -x ./uninstall.sh ]
  then
    chmod +x ./uninstall.sh
  fi

  source ./uninstall.sh

  cd ..

  echo -e "${BOLD_RED}Finished uninstall $(echo ${dir:2} | cut -d'_' -f 1)${NC}"
done

perl -0777 -p -i -e "s/(#### INSTALLER AUTOGENERATED ####)(.+?)(#{32,32})//sg" ~/.bashrc
