#!/bin/bash
nvm exec 7.2 fortune | cowsay -f `find /usr/share/cowsay/cows/ -type f | shuf -n 1` | rnbw -b $(( ( RANDOM % 10 )  + 1 ))

export PATH=$INSTALL_DATA_DIR/bin:$PATH
export VISUAL=vim
export EDITOR=vim
export TERM=xterm-256color

alias rmcd=". rmcd"
alias mkcd=". mkcd"

. keyswitch
