#!/bin/bash

command -v rnbw >/dev/null 2>&1 || { echo >&2 "I require rnbw but its not installed. Installing."; npm i -g rnbw;}
nvm exec 7.2 fortune | cowsay -f `find /usr/share/cowsay/cows/ -type f | shuf -n 1` | rnbw -b $(( ( RANDOM % 10 )  + 1 ))

export PATH=$INSTALL_DATA_DIR/bin:$PATH
export VISUAL=vim
export EDITOR=vim
export TERM=xterm-256color
#export PS1="\[\e[37;1m\]\$(date +"%I:%M") \$(pwd)\[\e[0m\e[34m\] λ\[\e[0m\] "
#export PS1="──── "
export PS1="PS1="\[\033[1;35m\]ᴊᴀᴄᴋ ᴅᴜᴘʟᴇssɪs\[\033[0m\] ""

# Run last command with 'sudo' prepended
alias please="sudo \$(fc -n -l -1)"
alias sta="git status"
alias adda="git add -A"
alias fracking="sudo"
alias rmcd=". rmcd"
alias mkcd=". mkcd"
alias say="espeak"
alias i3config="$EDITOR ~/.config/i3/config"
alias i3blocksconfig="$EDITOR ~/.config/i3blocks/config"
alias bashstart="$EDITOR $INSTALL_DATA_DIR/bash/bashstart"
alias neofetch="neofetch --config ~/.config/neofetch/config.conf --block_range 0 15"
alias p="pwd"

clone () {
  git clone https://github.com/"$1"
}

com () {
  git commit -m "$1"
}

push () {
  git push origin "$1"
}
